name: client
description: A new Flutter Boilerplate Example project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flavor: ^2.0.0
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate: true
  uses-material-design: true
  assets: 
    - assets/env/.env.prod
    - assets/env/.env.test 
    - assets/env/.env.dev
    - assets/env/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
