name: in_memory_users_data_source
description: An in-memory implementation of the UsersDataSource interface.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  users_data_source:
    path: ../users_data_source
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
